
base:
  base_url: http://127.0.0.1:8787
  base_wx_url: https://api.weixin.qq.com

mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456
  database: school
  charset: utf8

email:
  email_name: jftest222@163.com               # 发送邮件的邮箱
  email_password: TXpYgviRDh8aKJWi                # 发送邮件的邮箱密码
  email_port: 465                        # 发送邮件的端口号
  email_server: smtp.163.com        # 发送邮件的服务器地址
  email_receiver: jftest222@163.com       # 接收邮件的邮箱
  report_path: reports/allures/index.html