[host]
host = http://localhost:8080
port = 8080

[mysql]
host = localhost
port = 3306
username = root
password = 123456
database_gdc_admin = gdc_admin
database_gdc = gdc

[yaml]
## 默认的yaml配置读取
yaml_file_name = test.yaml


[headers]
data = {'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}
json = {'Content-Type': 'application/json;charset=UTF-8 '}